{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9a4e5b80-509a-4784-8389-46b2e7c88804",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-07 20:02:50.573 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import re\n",
    "# ============================\n",
    "# إعداد الصفحة (بدون SQL)\n",
    "# ============================\n",
    "st.set_page_config(page_title=\"Table Extractor\", layout=\"wide\")\n",
    "st.title(\"📊 استخراج وتصنيف الجداول\")\n",
    "st.write(\"ارفع ملف نصي (TXT) وسيتم استخراج أسماء الجداول وتصنيفها مع إمكانية تحميل النتائج.\")\n",
    "# ============================\n",
    "# تهيئة المتغيرات\n",
    "# ============================\n",
    "tables_unique = []\n",
    "admin_tables = []\n",
    "dp_tables = []\n",
    "no_schema_tables = []\n",
    "output_text = \"\"\n",
    "# ============================\n",
    "# رفع الملف\n",
    "# ============================\n",
    "uploaded_file = st.file_uploader(\"📂 ارفع ملف TXT\", type=[\"txt\"])\n",
    "def clean_table_name(name):\n",
    "   return name.strip('()[]{}\"').strip()\n",
    "# ============================\n",
    "# المعالجة\n",
    "# ============================\n",
    "if uploaded_file is not None:\n",
    "   try:\n",
    "       file_text = uploaded_file.read().decode(\"utf-8\")\n",
    "   except UnicodeDecodeError:\n",
    "       file_text = uploaded_file.read().decode(\"utf-8-sig\")\n",
    "   # تنظيف التعليقات\n",
    "   text_clean = re.sub(r'--.*', '', file_text)\n",
    "   text_clean = re.sub(r'/\\*.*?\\*/', '', text_clean, flags=re.DOTALL)\n",
    "   tables = []\n",
    "   # ============================\n",
    "   # استخراج أسماء الجداول\n",
    "   # ============================\n",
    "   from_pattern = r'\\bFROM\\s+([^\\s;]+(?:\\s*,\\s*[^\\s;]+)*)'\n",
    "   join_pattern = r'\\bJOIN\\s+([^\\s\\(\\);]+)'\n",
    "   for part in re.findall(from_pattern, text_clean, re.IGNORECASE):\n",
    "       for t in part.split(','):\n",
    "           name = t.split('#(lf)')[0].strip()\n",
    "           if name and not name.startswith('('):\n",
    "               tables.append(clean_table_name(name.split()[0]))\n",
    "   for t in re.findall(join_pattern, text_clean, re.IGNORECASE):\n",
    "       name = t.split('#(lf)')[0].strip()\n",
    "       if name and not name.startswith('('):\n",
    "           tables.append(clean_table_name(name.split()[0]))\n",
    "   # Views (Power Query)\n",
    "   view_pattern = r'Name\\s*=\\s*\"([^\"]+)\"'\n",
    "   for v in re.findall(view_pattern, text_clean):\n",
    "       tables.append(clean_table_name(v))\n",
    "   # إزالة التكرار\n",
    "   tables_unique = list(dict.fromkeys(tables))\n",
    "   # ============================\n",
    "   # التصنيف\n",
    "   # ============================\n",
    "   for table in tables_unique:\n",
    "       if '.' in table:\n",
    "           schema = table.split('.')[0].lower()\n",
    "           if 'omi' in schema:\n",
    "               admin_tables.append(table)\n",
    "           else:\n",
    "               dp_tables.append(table)\n",
    "       else:\n",
    "           no_schema_tables.append(table)\n",
    "   # ============================\n",
    "   # عرض النتائج\n",
    "   # ============================\n",
    "   st.success(f\"✅ عدد الجداول الكلي: {len(tables_unique)}\")\n",
    "   col1, col2, col3 = st.columns(3)\n",
    "   with col1:\n",
    "       st.subheader(\"📝 جداول الإدارة\")\n",
    "       st.write(admin_tables if admin_tables else \"لا يوجد\")\n",
    "   with col2:\n",
    "       st.subheader(\"📝 جداول المستودعات التقنية\")\n",
    "       st.write(dp_tables if dp_tables else \"لا يوجد\")\n",
    "   with col3:\n",
    "       st.subheader(\"📝 جداول بدون سكيما\")\n",
    "       st.write(no_schema_tables if no_schema_tables else \"لا يوجد\")\n",
    "   st.subheader(\"📋 جميع الجداول\")\n",
    "   st.write(tables_unique if tables_unique else \"لا توجد نتائج\")\n",
    "   # ============================\n",
    "   # تجهيز ملف TXT\n",
    "   # ============================\n",
    "   output_text += f\"عدد الجداول الكلي: {len(tables_unique)}\\n\\n\"\n",
    "   output_text += \"جداول الإدارة:\\n\"\n",
    "   for t in admin_tables:\n",
    "       output_text += f\"- {t}\\n\"\n",
    "   output_text += \"\\nجداول المستودعات التقنية:\\n\"\n",
    "   for t in dp_tables:\n",
    "       output_text += f\"- {t}\\n\"\n",
    "   output_text += \"\\nجداول بدون سكيما:\\n\"\n",
    "   for t in no_schema_tables:\n",
    "       output_text += f\"- {t}\\n\"\n",
    "   output_text += \"\\nجميع الجداول:\\n\"\n",
    "   for t in tables_unique:\n",
    "       output_text += f\"- {t}\\n\"\n",
    "   st.download_button(\n",
    "       label=\"⬇️ تحميل النتائج (TXT)\",\n",
    "       data=output_text,\n",
    "       file_name=\"tables_list.txt\",\n",
    "       mime=\"text/plain\"\n",
    "   )\n",
    "else:\n",
    "   st.info(\"⬆️ الرجاء رفع ملف TXT للبدء\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
